// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppToolApproval } from "./AppToolApproval";
import type { McpAppMessageApprovalMode } from "./McpAppMessageApprovalMode";

export type AppToolsConfig = { [key in string]?: { enabled: boolean | null, approval_mode: AppToolApproval | null, mcp_app_message_approval_mode: McpAppMessageApprovalMode | null, } };
