// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerUseMacosConfig } from "./ComputerUseMacosConfig";

export type ComputerUseConfig = { allow_persistent_approval: boolean | null, macos: ComputerUseMacosConfig | null, };
