// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Codex-managed host path created by `fs/createUpload`.
 */
export type FsCreateUploadResponse = {
/**
 * Absolute path where the client should stream staged upload bytes.
 */
path: AbsolutePathBuf, };
