// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Allocate a Codex-managed host path for a staged upload.
 */
export type FsCreateUploadParams = {
/**
 * User-visible file name. App-server stores only the final path component.
 */
fileName: string, };
