// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HooksListParams = {
/**
 * When omitted or empty, defaults to the current session working directory.
 */
cwds?: Array<string> | null, };
