// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageGenerationContent = { "type": "inline", dataBase64: string, mimeType: string | null, byteLength: number | null, } | { "type": "deferred", contentId: string, mimeType: string | null, byteLength: number | null, width: number | null, height: number | null, } | { "type": "unavailable", reason: string, };
