// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStartupState } from "./McpServerStartupState";

export type McpServerStatusUpdatedNotification = {
/**
 * Identifier of the thread whose `McpConnectionManager` produced this
 * update. Current servers always set this; it remains optional so older
 * app servers that omit the field still deserialize and route globally.
 */
threadId: string | null, name: string, status: McpServerStartupState, error: string | null, };
