// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStartupState } from "./McpServerStartupState";

export type McpServerStatusUpdatedNotification = {
/**
 * Identifier of the thread whose `McpConnectionManager` produced this
 * update. Always set on notifications emitted by current servers;
 * remains `Option` so legacy clients that omit the field still
 * deserialise and route as a global event.
 */
threadId: string | null, name: string, status: McpServerStartupState, error: string | null, };
