// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSourceRequirement } from "./SkillSourceRequirement";

export type SkillsRequirements = { allowedSources: Array<SkillSourceRequirement> | null, };
