// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

export type ThreadItemsListResponse = {
/**
 * Full ThreadItems for the requested turn page. Accumulate pages until `nextCursor` is null
 * to hydrate the client-side Turn representation.
 */
data: Array<ThreadItem>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * if None, there are no more items to return.
 */
nextCursor: string | null,
/**
 * Opaque cursor to pass as `cursor` when reversing `sortDirection`.
 * This is only populated when the page contains at least one item.
 * Use it with the opposite `sortDirection` to include the anchor item again
 * and catch updates to that item.
 */
backwardsCursor: string | null, };
