// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadItemContentReadResponse = {
/**
 * Media type of the returned content when known.
 */
mimeType: string | null,
/**
 * Base64-encoded content bytes.
 */
dataBase64: string,
/**
 * Decoded byte length when known.
 */
byteLength: number | null, };
