// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LargeContentMode } from "./LargeContentMode";
import type { SortDirection } from "./SortDirection";

export type ThreadItemsListParams = { threadId: string,
/**
 * Turn to hydrate after receiving a summary Turn from `thread/turns/list`.
 */
turnId: string,
/**
 * Controls whether large item payloads, such as generated image bytes, are embedded in
 * returned ThreadItems or replaced with deferred content references.
 *
 * Defaults to `inline` for compatibility. New clients should prefer `deferred`.
 */
largeContent?: LargeContentMode | null,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 */
cursor?: string | null,
/**
 * Optional item page size.
 */
limit?: number | null,
/**
 * Optional item pagination direction; defaults to ascending.
 */
sortDirection?: SortDirection | null, };
