// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LargeContentMode } from "./LargeContentMode";

export type ThreadReadParams = { threadId: string,
/**
 * Controls whether large item payloads, such as generated image bytes, are embedded in
 * returned ThreadItems or replaced with deferred content references.
 *
 * Defaults to `inline` for compatibility. New clients that may load large histories should
 * prefer `deferred` and fetch bytes on demand with `thread/item/content/read`.
 */
largeContent?: LargeContentMode | null,
/**
 * When true, include the traditional fully hydrated thread history:
 * `thread.turns` is populated and each returned Turn has `itemsView: "full"`.
 *
 * When false, `thread/read` returns metadata only. Clients can page history separately
 * with `thread/turns/list`, then hydrate individual summary turns with `thread/items/list`.
 */
includeTurns: boolean, };
